### ISSUE TITLE
Planned support for .NET Core RTM / .NET Standard

### ISSUE THREAD

**Issue by marchy** [zulfahmi93/HtmlAgilityPack.NetCore#3]
Hi there have you had a chance to look at porting this for the now-release .NET Core RTM that runs on .NET Standard as opposed to the .NET 4.6.x runtimes?

Cheers!

**Comment by zulfahmi93** [comment]
Hi,
I've merged pull request #2 which migrates this library to .NET Core RTM and targets .NET Standard 1.3 and I've updated the nuget package.

Thanks.

**Comment by marchy** [comment]
Fantastic thanks so much for being on it. Cheers!
