### ISSUE TITLE
[Question]: Status/Roadmap of this project

### ISSUE THREAD

**Issue by atifaziz** [zulfahmi93/HtmlAgilityPack.NetCore#4]
Thanks for putting this together. Seems like a step in the right direction but what's the status or roadmap of this project with respect to the [original HTML Agility Pack project](http://htmlagilitypack.codeplex.com/) as well as other forks? For example, I've noticed some [renewed activity in the project on CodePlex](http://htmlagilitypack.codeplex.com/SourceControl/list/changesets), including several new versions published to NuGet ([1.4.9.1](https://www.nuget.org/packages/HtmlAgilityPack/1.4.9.1)&hellip;[1.4.9.5](https://www.nuget.org/packages/HtmlAgilityPack/1.4.9.5) so far this year) so will those be rolled here eventually? Then [there's another fork](https://github.com/noliar/HtmlAgilityPack.NetCore) that seems to be in similar vein as this one. Wouldn't it make sense to consolidate efforts here?

**Comment by ricardoalcantara** [comment]
Hi,
I am also interested in it. Currently I keep another "fork" from the original repository from codeplex and the Fizzler for HtmlAgilityPack both ported myself, and I believe this is not "cool" for the community.

**Comment by linezero** [comment]
Hi,I am want need use it,but before no know this.Source from codeplex ,I just migrate to .NET Core.

**Comment by ricardoalcantara** [comment]
What?

**Comment by atifaziz** [comment]
@ricardoalcantara I think what @linezero is trying to say is that:

> I am want need use it

He needed HTML Agility Pack for .NET Core…

> but before no know this.

…but did not know about this version/repo at the time…

> Source from codeplex

…so he took the source code from CodePlex…

> I just migrate to .NET Core

…and migrated it to .NET Core.

Anyway, that's how I read it.

**Comment by linezero** [comment]
@atifaziz Thank you read it.

**Comment by zulfahmi93** [comment]
Hi,

My situation is same as @linezero. I need to use HTML Agility Pack for my UWP and ASP.NET Core project. When I search for any existing repo for this library which is compatible with both frameworks, there's none. I think we should continue the work for this library on the repo by @noliar as it includes unit tests and I have no knowledge on HTML parsing.

**Comment by atifaziz** [comment]
@zulfahmi93 @linezero Thanks for your answers. I'm going to close this question and hopefully we can resume the discussion about consolidating the effort over at noliar/HtmlAgilityPack.NetCore#1.
